---
- name: "create ~/backend directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy artifact to ~/backend directory"
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    backup: yes

- name: "Unzip artifacts in ~/backend"
  shell: |
    tar -xvf artifact.tar.gz
  args:
    chdir: /home/ubuntu/backend

- name: "Start server"
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: /home/ubuntu/backend
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
